"tuning_type": "BayesFT"
"model_name": "deepfake_detection"
"real_folder": ['Real_4k_split', 'Real_1k_split']
"fake_folder": ['StableDiffusion_split', 'StyleGAN2_split', 'Midjourney_split', 'firefly_split', 'Dall-E_split']
"num_epochs": 5
"batch_size": 16
"learning_rate": 0.00035
"use_wandb": False

# BayesTune Parameters
"sparsity_level": 0.00045
"lr_model": 0.0005
"lr_lambda": 0.0005
"N_exp": 12
"burnin_steps": 2000
"thinning_steps": 25
"warmup_steps": 1000
"num_epochs_sampling": 10
"batch_size_sampling": 4