"tuning_type": "FullFT"
"model_name": "deepfake_detection"
"real_folder": ['Real_4k_split', 'Real_1k_split']
"fake_folder": ['StableDiffusion_split', 'StyleGAN2_split', 'Midjourney_split', 'firefly_split', 'Dall-E_split']
"num_epochs": 10
"batch_size": 16
"learning_rate": 0.0005
"use_wandb": False