"tuning_type": "FullFT"
"model_name": "efficientnetv2_rw_m.agc_in1k"
"real_folder": "Real_split"
"fake_folder": "StyleGAN_split"
"num_epochs": 100
"batch_size": 16
"learning_rate": 0.0005
"use_wandb": False